version: '3.7'
services:
  mongodb:
    image: mongo:6.0.6
    hostname: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: clpl
      MONGO_INITDB_ROOT_PASSWORD: clpl
    volumes:
      - ./data/mongodb:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
    - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
    - ME_CONFIG_MONGODB_URL=mongodb://clpl:clpl@mongodb:27017
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    ports:
      - "28081:8081"
