[supervisord]
nodaemon=true

[program:apiserver]
command=python -m src.apiserver
autostart=true
autorestart=true
startretries=3

[program:rbacserver]
command=python -m src.rbacserver
autostart=true
autorestart=true
startretries=3
