# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clpl_apiserver_client.models.user_model_v1 import UserModelV1

class TestUserModelV1(unittest.TestCase):
    """UserModelV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserModelV1:
        """Test UserModelV1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserModelV1`
        """
        model = UserModelV1()
        if include_optional:
            return UserModelV1(
                version = '',
                resource_status = 'committed',
                uid = 56,
                uuid = '',
                username = '',
                status = 'active',
                email = '',
                password = '',
                htpasswd = '',
                role = 'super_admin',
                owned_pod_ids = [
                    ''
                    ],
                quota = clpl_apiserver_client.models.quota_model.QuotaModel(
                    version = '', 
                    committed = True, 
                    cpu_m = 56, 
                    memory_mb = 56, 
                    storage_mb = 56, 
                    gpu = 56, 
                    network_mb = 56, 
                    pod_n = 56, ),
                extra_info = None
            )
        else:
            return UserModelV1(
                version = '',
                uid = 56,
                uuid = '',
                username = '',
                email = '',
                password = '',
                role = 'super_admin',
                owned_pod_ids = [
                    ''
                    ],
                quota = clpl_apiserver_client.models.quota_model.QuotaModel(
                    version = '', 
                    committed = True, 
                    cpu_m = 56, 
                    memory_mb = 56, 
                    storage_mb = 56, 
                    gpu = 56, 
                    network_mb = 56, 
                    pod_n = 56, ),
        )
        """

    def testUserModelV1(self):
        """Test UserModelV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
