# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clpl_apiserver_client.api.policy_api import PolicyApi


class TestPolicyApi(unittest.TestCase):
    """PolicyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PolicyApi()

    def tearDown(self) -> None:
        pass

    def test_postpolicy_policy_add(self) -> None:
        """Test case for postpolicy_policy_add

        Add a raw policy to enforcer cache
        """
        pass

    def test_postpolicy_policy_reload(self) -> None:
        """Test case for postpolicy_policy_reload

        Reload the policy from the database.
        """
        pass


if __name__ == '__main__':
    unittest.main()
