# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clpl_apiserver_client.models.pod_model_v1 import PodModelV1

class TestPodModelV1(unittest.TestCase):
    """PodModelV1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PodModelV1:
        """Test PodModelV1
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PodModelV1`
        """
        model = PodModelV1()
        if include_optional:
            return PodModelV1(
                version = '',
                resource_status = 'committed',
                pod_id = '',
                name = '',
                description = '',
                template_ref = '',
                template_str = '',
                cpu_lim_m_cpu = 56,
                mem_lim_mb = 56,
                storage_lim_mb = 56,
                username = '',
                user_uuid = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                accessed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                timeout_s = 56,
                current_status = 'pending',
                target_status = 'pending'
            )
        else:
            return PodModelV1(
                version = '',
                pod_id = '',
                name = '',
                description = '',
                template_ref = '',
                template_str = '',
                cpu_lim_m_cpu = 56,
                mem_lim_mb = 56,
                storage_lim_mb = 56,
                username = '',
                user_uuid = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                accessed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                timeout_s = 56,
                current_status = 'pending',
                target_status = 'pending',
        )
        """

    def testPodModelV1(self):
        """Test PodModelV1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
