# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clpl_rbacserver_client.models.response_base_model import ResponseBaseModel

class TestResponseBaseModel(unittest.TestCase):
    """ResponseBaseModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseBaseModel:
        """Test ResponseBaseModel
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseBaseModel`
        """
        model = ResponseBaseModel()
        if include_optional:
            return ResponseBaseModel(
                description = '',
                status = 56,
                message = ''
            )
        else:
            return ResponseBaseModel(
                status = 56,
                message = '',
        )
        """

    def testResponseBaseModel(self):
        """Test ResponseBaseModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
