# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clpl_apiserver_client.models.enforce_request import EnforceRequest

class TestEnforceRequest(unittest.TestCase):
    """EnforceRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnforceRequest:
        """Test EnforceRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnforceRequest`
        """
        model = EnforceRequest()
        if include_optional:
            return EnforceRequest(
                subject = '',
                object = '',
                action = ''
            )
        else:
            return EnforceRequest(
        )
        """

    def testEnforceRequest(self):
        """Test EnforceRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
