# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clpl_apiserver_client.models.enforce_response import EnforceResponse

class TestEnforceResponse(unittest.TestCase):
    """EnforceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnforceResponse:
        """Test EnforceResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnforceResponse`
        """
        model = EnforceResponse()
        if include_optional:
            return EnforceResponse(
                description = '',
                status = 56,
                message = '',
                result = True
            )
        else:
            return EnforceResponse(
                status = 56,
                message = '',
        )
        """

    def testEnforceResponse(self):
        """Test EnforceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
