# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clpl_apiserver_client.models.template_model import TemplateModel

class TestTemplateModel(unittest.TestCase):
    """TemplateModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplateModel:
        """Test TemplateModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplateModel`
        """
        model = TemplateModel()
        if include_optional:
            return TemplateModel(
                version = '',
                resource_status = 'committed',
                template_id = '',
                name = '',
                description = '',
                image_ref = '',
                template_str = '',
                fields = {
                    'key' : 'str'
                    },
                defaults = None
            )
        else:
            return TemplateModel(
                version = '',
                template_id = '',
                name = '',
                description = '',
                image_ref = '',
                template_str = '',
                fields = {
                    'key' : 'str'
                    },
                defaults = None,
        )
        """

    def testTemplateModel(self):
        """Test TemplateModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
