# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clpl_rbacserver_client.models.rbac_policy_exchange_model_v2 import RBACPolicyExchangeModelV2

class TestRBACPolicyExchangeModelV2(unittest.TestCase):
    """RBACPolicyExchangeModelV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RBACPolicyExchangeModelV2:
        """Test RBACPolicyExchangeModelV2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RBACPolicyExchangeModelV2`
        """
        model = RBACPolicyExchangeModelV2()
        if include_optional:
            return RBACPolicyExchangeModelV2(
                policies = [
                    null
                    ]
            )
        else:
            return RBACPolicyExchangeModelV2(
        )
        """

    def testRBACPolicyExchangeModelV2(self):
        """Test RBACPolicyExchangeModelV2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
