# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clpl_apiserver_client.models.user_status_enum import UserStatusEnum

class TestUserStatusEnum(unittest.TestCase):
    """UserStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserStatusEnum(self):
        """Test UserStatusEnum"""
        # inst = UserStatusEnum()

if __name__ == '__main__':
    unittest.main()
