# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clpl_apiserver_client.models.quota_model import QuotaModel

class TestQuotaModel(unittest.TestCase):
    """QuotaModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuotaModel:
        """Test QuotaModel
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuotaModel`
        """
        model = QuotaModel()
        if include_optional:
            return QuotaModel(
                version = '',
                committed = True,
                cpu_m = 56,
                memory_mb = 56,
                storage_mb = 56,
                gpu = 56,
                network_mb = 56,
                pod_n = 56
            )
        else:
            return QuotaModel(
                version = '',
                cpu_m = 56,
                memory_mb = 56,
                storage_mb = 56,
                gpu = 56,
                network_mb = 56,
                pod_n = 56,
        )
        """

    def testQuotaModel(self):
        """Test QuotaModel"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
