# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clpl_apiserver_client.models.user_role_enum import UserRoleEnum

class TestUserRoleEnum(unittest.TestCase):
    """UserRoleEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserRoleEnum(self):
        """Test UserRoleEnum"""
        # inst = UserRoleEnum()

if __name__ == '__main__':
    unittest.main()
