# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clpl_rbacserver_client.api.enforce_api import EnforceApi


class TestEnforceApi(unittest.TestCase):
    """EnforceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EnforceApi()

    def tearDown(self) -> None:
        pass

    def test_postenforce_enforce_post(self) -> None:
        """Test case for postenforce_enforce_post

        Enforce the request against the policy and model, return the result.
        """
        pass


if __name__ == '__main__':
    unittest.main()
