from src import CONFIG_PROJECT_NAME

CONFIG_AUTH_COOKIES_NAME = f"{CONFIG_PROJECT_NAME}_auth_token"
CONFIG_PROXY_ORIGIN_URL_HEADER = "x-original-url"
CONFIG_LOG_PATH_KEY = CONFIG_PROJECT_NAME.upper() + "_LOG_PATH"
CONFIG_LOG_PATH_DEFAULT = "./logs/apiserver"
CONFIG_K8S_CREDENTIAL_FMT = "{}-basic-auth"
CONFIG_K8S_DEPLOYMENT_FMT = f"{CONFIG_PROJECT_NAME}-{{}}"
CONFIG_K8S_POD_LABEL_FMT = f"apps.{CONFIG_PROJECT_NAME}-{{}}"
CONFIG_K8S_POD_LABEL_KEY = "k8s-app"
CONFIG_K8S_SERVICE_FMT = f"{CONFIG_PROJECT_NAME}-svc-{{}}"
CONFIG_SCAN_POD_INTERVAL_S = 120
CONFIG_HEARTBEAT_INTERVAL_S = 120
CONFIG_SHUTDOWN_GRACE_PERIOD_S = 60

from .config import (
    APIServerConfig, OIDCConfig, SiteConfig,
    CONFIG_DEFAULT_CONFIG_PATH,
)
