#apiVersion: v1
#kind: Namespace
#metadata:
#  name: clpl
#---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: clpl-admin
  namespace: clpl
---
apiVersion: v1
kind: Secret
metadata:
  name: clpl-admin-secret
  namespace: clpl
  annotations:
    kubernetes.io/service-account.name: clpl-admin
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: clpl-namespace-admin
  namespace: clpl
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clpl-namespace-admin-binding
  namespace: clpl
subjects:
- kind: ServiceAccount
  name: clpl-admin
  namespace: clpl
roleRef:
  kind: Role
  name: clpl-namespace-admin
  apiGroup: rbac.authorization.k8s.io