version: '3.8'
services:
  clash:
    image: dreamacro/clash-premium
    container_name: clash-premium
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
      - ./ui:/ui # 图形面板目录
    ports:
      - "7890:7890"
      - "9090:9090"
    restart: unless-stopped
    network_mode: "bridge"