# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from clpl_apiserver_client.models.pod_status_enum import PodStatusEnum
from clpl_apiserver_client.models.resource_status_enum import ResourceStatusEnum
from typing import Optional, Set
from typing_extensions import Self

class PodModelV1(BaseModel):
    """
    Pod model, used to define pod
    """ # noqa: E501
    version: StrictStr
    resource_status: Optional[ResourceStatusEnum] = None
    pod_id: StrictStr
    name: StrictStr
    description: StrictStr
    template_ref: StrictStr
    template_str: Optional[StrictStr]
    cpu_lim_m_cpu: StrictInt
    mem_lim_mb: StrictInt
    storage_lim_mb: StrictInt
    username: StrictStr
    user_uuid: StrictStr
    created_at: datetime
    started_at: datetime
    accessed_at: datetime
    timeout_s: StrictInt
    current_status: PodStatusEnum
    target_status: PodStatusEnum
    __properties: ClassVar[List[str]] = ["version", "resource_status", "pod_id", "name", "description", "template_ref", "template_str", "cpu_lim_m_cpu", "mem_lim_mb", "storage_lim_mb", "username", "user_uuid", "created_at", "started_at", "accessed_at", "timeout_s", "current_status", "target_status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PodModelV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if template_str (nullable) is None
        # and model_fields_set contains the field
        if self.template_str is None and "template_str" in self.model_fields_set:
            _dict['template_str'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PodModelV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "resource_status": obj.get("resource_status"),
            "pod_id": obj.get("pod_id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "template_ref": obj.get("template_ref"),
            "template_str": obj.get("template_str"),
            "cpu_lim_m_cpu": obj.get("cpu_lim_m_cpu"),
            "mem_lim_mb": obj.get("mem_lim_mb"),
            "storage_lim_mb": obj.get("storage_lim_mb"),
            "username": obj.get("username"),
            "user_uuid": obj.get("user_uuid"),
            "created_at": obj.get("created_at"),
            "started_at": obj.get("started_at"),
            "accessed_at": obj.get("accessed_at"),
            "timeout_s": obj.get("timeout_s"),
            "current_status": obj.get("current_status"),
            "target_status": obj.get("target_status")
        })
        return _obj


