# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from clpl_apiserver_client.models.field_type_enum import FieldTypeEnum
from clpl_apiserver_client.models.resource_status_enum import ResourceStatusEnum
from typing import Optional, Set
from typing_extensions import Self

class TemplateModel(BaseModel):
    """
    Template model, used to define template
    """ # noqa: E501
    version: StrictStr
    resource_status: Optional[ResourceStatusEnum] = None
    template_id: StrictStr
    name: StrictStr
    description: StrictStr
    image_ref: StrictStr
    template_str: StrictStr
    fields: Optional[Dict[str, FieldTypeEnum]]
    defaults: Optional[Dict[str, Any]]
    __properties: ClassVar[List[str]] = ["version", "resource_status", "template_id", "name", "description", "image_ref", "template_str", "fields", "defaults"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TemplateModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if fields (nullable) is None
        # and model_fields_set contains the field
        if self.fields is None and "fields" in self.model_fields_set:
            _dict['fields'] = None

        # set to None if defaults (nullable) is None
        # and model_fields_set contains the field
        if self.defaults is None and "defaults" in self.model_fields_set:
            _dict['defaults'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TemplateModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "resource_status": obj.get("resource_status"),
            "template_id": obj.get("template_id"),
            "name": obj.get("name"),
            "description": obj.get("description"),
            "image_ref": obj.get("image_ref"),
            "template_str": obj.get("template_str"),
            "fields": dict((_k, _v) for _k, _v in obj.get("fields").items()),
            "defaults": obj.get("defaults")
        })
        return _obj


