# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class UserRoleEnum(str, Enum):
    """
    UserRoleEnum
    """

    """
    allowed enum values
    """
    SUPER_ADMIN = 'super_admin'
    ADMIN = 'admin'
    USER = 'user'
    DEVICE = 'device'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of UserRoleEnum from a JSON string"""
        return cls(json.loads(json_str))


