# coding: utf-8

"""
    API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, SecretStr, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from clpl_apiserver_client.models.quota_model import QuotaModel
from clpl_apiserver_client.models.resource_status_enum import ResourceStatusEnum
from clpl_apiserver_client.models.user_role_enum import UserRoleEnum
from clpl_apiserver_client.models.user_status_enum import UserStatusEnum
from typing import Optional, Set
from typing_extensions import Self

class UserModelV1(BaseModel):
    """
    User model, used to define user
    """ # noqa: E501
    version: StrictStr
    resource_status: Optional[ResourceStatusEnum] = None
    uid: StrictInt
    uuid: Optional[StrictStr]
    username: StrictStr
    status: Optional[UserStatusEnum] = None
    email: Optional[StrictStr]
    password: SecretStr
    htpasswd: Optional[SecretStr] = None
    role: UserRoleEnum
    owned_pod_ids: List[StrictStr]
    quota: Optional[QuotaModel]
    extra_info: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["version", "resource_status", "uid", "uuid", "username", "status", "email", "password", "htpasswd", "role", "owned_pod_ids", "quota", "extra_info"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserModelV1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of quota
        if self.quota:
            _dict['quota'] = self.quota.to_dict()
        # set to None if uuid (nullable) is None
        # and model_fields_set contains the field
        if self.uuid is None and "uuid" in self.model_fields_set:
            _dict['uuid'] = None

        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if htpasswd (nullable) is None
        # and model_fields_set contains the field
        if self.htpasswd is None and "htpasswd" in self.model_fields_set:
            _dict['htpasswd'] = None

        # set to None if quota (nullable) is None
        # and model_fields_set contains the field
        if self.quota is None and "quota" in self.model_fields_set:
            _dict['quota'] = None

        # set to None if extra_info (nullable) is None
        # and model_fields_set contains the field
        if self.extra_info is None and "extra_info" in self.model_fields_set:
            _dict['extra_info'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserModelV1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "resource_status": obj.get("resource_status"),
            "uid": obj.get("uid"),
            "uuid": obj.get("uuid"),
            "username": obj.get("username"),
            "status": obj.get("status"),
            "email": obj.get("email"),
            "password": obj.get("password"),
            "htpasswd": obj.get("htpasswd"),
            "role": obj.get("role"),
            "owned_pod_ids": obj.get("owned_pod_ids"),
            "quota": QuotaModel.from_dict(obj["quota"]) if obj.get("quota") is not None else None,
            "extra_info": obj.get("extra_info")
        })
        return _obj


