"""
This module contains all the errors that can be raised by the application.
"""

db_connection_error = Exception("db connection error")
duplicate_username = Exception("duplicate username")
empty_username_or_password = Exception("empty username or password")
header_malformed = Exception("header malformed")
header_missing = Exception("header missing")
invalid_request_body = Exception("invalid request body")
invalid_token = Exception("invalid token")
k8s_config_not_found = Exception("Kubernetes config not found")
k8s_failed_to_create = Exception("Kubernetes failed to create")
k8s_failed_to_delete = Exception("Kubernetes failed to delete")
k8s_failed_to_get = Exception("Kubernetes failed to get")
k8s_failed_to_list = Exception("Kubernetes failed to list")
k8s_failed_to_update = Exception("Kubernetes failed to update")
k8s_timeout = Exception("Kubernetes timeout")
old_password_required = Exception("old password required")
otp_code_required = Exception("otp code required")
otp_code_wrong = Exception("otp code wrong")
otp_password_required = Exception("otp password required")
pod_not_found = Exception("pod not found")
policy_not_found = Exception("policy not found")
policy_cannot_be_deleted = Exception("policy cannot be deleted")
policy_cannot_be_modified = Exception("policy cannot be modified")
quota_exceeded = Exception("quota exceeded")
template_invalid = Exception("template invalid")
template_key_not_exists = BaseException("template key not exists")
template_key_not_used = Exception("template key not used")
template_not_found = Exception("template not found")
unknown_error = Exception("unknown error")
user_not_found = Exception("user not found")
user_not_allowed = Exception("user not allowed")
user_failed_to_parse = Exception("user failed to parse")
user_exists = Exception("user exists")
username_required = Exception("username required")
username_illegal = Exception("username illegal")
wrong_password = Exception("wrong password")
wrong_pod_profile = Exception("wrong pod profile")
wrong_query_filter = Exception("wrong query filter")
wrong_template_profile = Exception("wrong template profile")
wrong_user_profile = Exception("wrong user profile")
